# Generated by Django 2.2.28 on 2023-02-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('date_time', models.DateTimeField()),
                ('writer', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=1024)),
            ],
        ),
    ]
